name: flutter_infinite_list
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  leak_tracker:
  bloc: ^9.0.0
  provider: 
  bloc_concurrency: ^0.3.0
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  go_router: ^14.0.0
  http: ^1.0.0
  stream_transform: ^2.0.0

dev_dependencies:
  leak_tracker_testing:
  bloc_lint: ^0.3.0
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
