# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build_dev do
    match(
      type: "development",
      readonly: true,          # pull only, don't modify      
    )
    build_app(
      scheme: "Runner",
      workspace: "ios/Runner.xcworkspace",
      include_bitcode: true,
      export_method: "development",
      output_directory: "./build/ios",
      output_name: "debug.ipa",
    )
  end
end
